name: i2stonk
channels:
  - conda-forge
dependencies:
  - pandas
  - websockets
  - numpy
  - praw
  - scipy
  - pip:
    - ccxt
    - yfinance
    - yahoofinancials
    - git+https://github.com/Binance-docs/Binance_Futures_python.git
    - telethon
