name: i2stonk
channels:
  - conda-forge
  - numba
  - intel
dependencies:
  - python=3.8
  - pandas
  - websockets
  - numpy
  - xeus-sqlite
  - praw
  - h5py
  - pyyaml
  - numba
  - flit
  - scipy
  - matplotlib
  # acceleration
  - icc_rt  # -c numba
  - intelpython3_full  # -c intel
  - pip:
    - nptyping
    - ccxt
    - yfinance
    - yahoofinancials
    - git+https://github.com/Binance-docs/Binance_Futures_python.git
    - telethon
    - stockstats
