name: i2stonk
channels:
  - conda-forge
dependencies:
  - numpy
  - praw
  - pip:
    - ccxt
    - yfinance
    - yahoofinancials
    - stocksxsdk
    - git+https://github.com/Binance-docs/Binance_Futures_python.git
    - telethon
